# coding: utf-8

"""
    Geolocate API

    GeolocateAPI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class IPinfo(BaseModel):
    """
    IPinfo
    """ # noqa: E501
    feedback_url: Optional[StrictStr] = None
    exit_ip: Optional[StrictStr] = None
    capital: Optional[StrictStr] = None
    country_code: Optional[StrictStr] = None
    country_name: Optional[StrictStr] = None
    country_region: Optional[StrictStr] = None
    time_zone: Optional[StrictStr] = None
    domain_name: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    flag_url: Optional[StrictStr] = None
    domains: Optional[List[StrictStr]] = None
    call_codes: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["feedback_url", "exit_ip", "capital", "country_code", "country_name", "country_region", "time_zone", "domain_name", "currency", "flag_url", "domains", "call_codes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IPinfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IPinfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "feedback_url": obj.get("feedback_url"),
            "exit_ip": obj.get("exit_ip"),
            "capital": obj.get("capital"),
            "country_code": obj.get("country_code"),
            "country_name": obj.get("country_name"),
            "country_region": obj.get("country_region"),
            "time_zone": obj.get("time_zone"),
            "domain_name": obj.get("domain_name"),
            "currency": obj.get("currency"),
            "flag_url": obj.get("flag_url"),
            "domains": obj.get("domains"),
            "call_codes": obj.get("call_codes")
        })
        return _obj


