/*
Geolocate API

GeolocateAPI

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Agent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Agent{}

// Agent struct for Agent
type Agent struct {
	IsAgent     *bool   `json:"is_agent,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
}

// NewAgent instantiates a new Agent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgent() *Agent {
	this := Agent{}
	return &this
}

// NewAgentWithDefaults instantiates a new Agent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentWithDefaults() *Agent {
	this := Agent{}
	return &this
}

// GetIsAgent returns the IsAgent field value if set, zero value otherwise.
func (o *Agent) GetIsAgent() bool {
	if o == nil || IsNil(o.IsAgent) {
		var ret bool
		return ret
	}
	return *o.IsAgent
}

// GetIsAgentOk returns a tuple with the IsAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetIsAgentOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAgent) {
		return nil, false
	}
	return o.IsAgent, true
}

// HasIsAgent returns a boolean if a field has been set.
func (o *Agent) HasIsAgent() bool {
	if o != nil && !IsNil(o.IsAgent) {
		return true
	}

	return false
}

// SetIsAgent gets a reference to the given bool and assigns it to the IsAgent field.
func (o *Agent) SetIsAgent(v bool) {
	o.IsAgent = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *Agent) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *Agent) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *Agent) SetServiceName(v string) {
	o.ServiceName = &v
}

func (o Agent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Agent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsAgent) {
		toSerialize["is_agent"] = o.IsAgent
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	return toSerialize, nil
}

type NullableAgent struct {
	value *Agent
	isSet bool
}

func (v NullableAgent) Get() *Agent {
	return v.value
}

func (v *NullableAgent) Set(val *Agent) {
	v.value = val
	v.isSet = true
}

func (v NullableAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgent(val *Agent) *NullableAgent {
	return &NullableAgent{value: val, isSet: true}
}

func (v NullableAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
