/*
Geolocate API

GeolocateAPI

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Privacy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Privacy{}

// Privacy struct for Privacy
type Privacy struct {
	IsProxy     *bool   `json:"is_proxy,omitempty"`
	IsRelay     *bool   `json:"is_relay,omitempty"`
	IsTor       *bool   `json:"is_tor,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
}

// NewPrivacy instantiates a new Privacy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivacy() *Privacy {
	this := Privacy{}
	return &this
}

// NewPrivacyWithDefaults instantiates a new Privacy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivacyWithDefaults() *Privacy {
	this := Privacy{}
	return &this
}

// GetIsProxy returns the IsProxy field value if set, zero value otherwise.
func (o *Privacy) GetIsProxy() bool {
	if o == nil || IsNil(o.IsProxy) {
		var ret bool
		return ret
	}
	return *o.IsProxy
}

// GetIsProxyOk returns a tuple with the IsProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Privacy) GetIsProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsProxy) {
		return nil, false
	}
	return o.IsProxy, true
}

// HasIsProxy returns a boolean if a field has been set.
func (o *Privacy) HasIsProxy() bool {
	if o != nil && !IsNil(o.IsProxy) {
		return true
	}

	return false
}

// SetIsProxy gets a reference to the given bool and assigns it to the IsProxy field.
func (o *Privacy) SetIsProxy(v bool) {
	o.IsProxy = &v
}

// GetIsRelay returns the IsRelay field value if set, zero value otherwise.
func (o *Privacy) GetIsRelay() bool {
	if o == nil || IsNil(o.IsRelay) {
		var ret bool
		return ret
	}
	return *o.IsRelay
}

// GetIsRelayOk returns a tuple with the IsRelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Privacy) GetIsRelayOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRelay) {
		return nil, false
	}
	return o.IsRelay, true
}

// HasIsRelay returns a boolean if a field has been set.
func (o *Privacy) HasIsRelay() bool {
	if o != nil && !IsNil(o.IsRelay) {
		return true
	}

	return false
}

// SetIsRelay gets a reference to the given bool and assigns it to the IsRelay field.
func (o *Privacy) SetIsRelay(v bool) {
	o.IsRelay = &v
}

// GetIsTor returns the IsTor field value if set, zero value otherwise.
func (o *Privacy) GetIsTor() bool {
	if o == nil || IsNil(o.IsTor) {
		var ret bool
		return ret
	}
	return *o.IsTor
}

// GetIsTorOk returns a tuple with the IsTor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Privacy) GetIsTorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTor) {
		return nil, false
	}
	return o.IsTor, true
}

// HasIsTor returns a boolean if a field has been set.
func (o *Privacy) HasIsTor() bool {
	if o != nil && !IsNil(o.IsTor) {
		return true
	}

	return false
}

// SetIsTor gets a reference to the given bool and assigns it to the IsTor field.
func (o *Privacy) SetIsTor(v bool) {
	o.IsTor = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *Privacy) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Privacy) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *Privacy) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *Privacy) SetServiceName(v string) {
	o.ServiceName = &v
}

func (o Privacy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Privacy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsProxy) {
		toSerialize["is_proxy"] = o.IsProxy
	}
	if !IsNil(o.IsRelay) {
		toSerialize["is_relay"] = o.IsRelay
	}
	if !IsNil(o.IsTor) {
		toSerialize["is_tor"] = o.IsTor
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	return toSerialize, nil
}

type NullablePrivacy struct {
	value *Privacy
	isSet bool
}

func (v NullablePrivacy) Get() *Privacy {
	return v.value
}

func (v *NullablePrivacy) Set(val *Privacy) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivacy) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivacy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivacy(val *Privacy) *NullablePrivacy {
	return &NullablePrivacy{value: val, isSet: true}
}

func (v NullablePrivacy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivacy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
