/*
Geolocate API

GeolocateAPI

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ASN type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ASN{}

// ASN struct for ASN
type ASN struct {
	AutonomousSystemNumber       *int32  `json:"autonomous_system_number,omitempty"`
	AutonomousSystemOrganization *string `json:"autonomous_system_organization,omitempty"`
}

// NewASN instantiates a new ASN object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewASN() *ASN {
	this := ASN{}
	return &this
}

// NewASNWithDefaults instantiates a new ASN object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewASNWithDefaults() *ASN {
	this := ASN{}
	return &this
}

// GetAutonomousSystemNumber returns the AutonomousSystemNumber field value if set, zero value otherwise.
func (o *ASN) GetAutonomousSystemNumber() int32 {
	if o == nil || IsNil(o.AutonomousSystemNumber) {
		var ret int32
		return ret
	}
	return *o.AutonomousSystemNumber
}

// GetAutonomousSystemNumberOk returns a tuple with the AutonomousSystemNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASN) GetAutonomousSystemNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.AutonomousSystemNumber) {
		return nil, false
	}
	return o.AutonomousSystemNumber, true
}

// HasAutonomousSystemNumber returns a boolean if a field has been set.
func (o *ASN) HasAutonomousSystemNumber() bool {
	if o != nil && !IsNil(o.AutonomousSystemNumber) {
		return true
	}

	return false
}

// SetAutonomousSystemNumber gets a reference to the given int32 and assigns it to the AutonomousSystemNumber field.
func (o *ASN) SetAutonomousSystemNumber(v int32) {
	o.AutonomousSystemNumber = &v
}

// GetAutonomousSystemOrganization returns the AutonomousSystemOrganization field value if set, zero value otherwise.
func (o *ASN) GetAutonomousSystemOrganization() string {
	if o == nil || IsNil(o.AutonomousSystemOrganization) {
		var ret string
		return ret
	}
	return *o.AutonomousSystemOrganization
}

// GetAutonomousSystemOrganizationOk returns a tuple with the AutonomousSystemOrganization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ASN) GetAutonomousSystemOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.AutonomousSystemOrganization) {
		return nil, false
	}
	return o.AutonomousSystemOrganization, true
}

// HasAutonomousSystemOrganization returns a boolean if a field has been set.
func (o *ASN) HasAutonomousSystemOrganization() bool {
	if o != nil && !IsNil(o.AutonomousSystemOrganization) {
		return true
	}

	return false
}

// SetAutonomousSystemOrganization gets a reference to the given string and assigns it to the AutonomousSystemOrganization field.
func (o *ASN) SetAutonomousSystemOrganization(v string) {
	o.AutonomousSystemOrganization = &v
}

func (o ASN) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ASN) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutonomousSystemNumber) {
		toSerialize["autonomous_system_number"] = o.AutonomousSystemNumber
	}
	if !IsNil(o.AutonomousSystemOrganization) {
		toSerialize["autonomous_system_organization"] = o.AutonomousSystemOrganization
	}
	return toSerialize, nil
}

type NullableASN struct {
	value *ASN
	isSet bool
}

func (v NullableASN) Get() *ASN {
	return v.value
}

func (v *NullableASN) Set(val *ASN) {
	v.value = val
	v.isSet = true
}

func (v NullableASN) IsSet() bool {
	return v.isSet
}

func (v *NullableASN) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableASN(val *ASN) *NullableASN {
	return &NullableASN{value: val, isSet: true}
}

func (v NullableASN) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableASN) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
