/*
Geolocate API

GeolocateAPI

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IPinfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPinfo{}

// IPinfo struct for IPinfo
type IPinfo struct {
	FeedbackUrl   *string  `json:"feedback_url,omitempty"`
	ExitIp        *string  `json:"exit_ip,omitempty"`
	Capital       *string  `json:"capital,omitempty"`
	CountryCode   *string  `json:"country_code,omitempty"`
	CountryName   *string  `json:"country_name,omitempty"`
	CountryRegion *string  `json:"country_region,omitempty"`
	TimeZone      *string  `json:"time_zone,omitempty"`
	DomainName    *string  `json:"domain_name,omitempty"`
	Currency      *string  `json:"currency,omitempty"`
	FlagUrl       *string  `json:"flag_url,omitempty"`
	Domains       []string `json:"domains,omitempty"`
	CallCodes     []string `json:"call_codes,omitempty"`
}

// NewIPinfo instantiates a new IPinfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPinfo() *IPinfo {
	this := IPinfo{}
	return &this
}

// NewIPinfoWithDefaults instantiates a new IPinfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPinfoWithDefaults() *IPinfo {
	this := IPinfo{}
	return &this
}

// GetFeedbackUrl returns the FeedbackUrl field value if set, zero value otherwise.
func (o *IPinfo) GetFeedbackUrl() string {
	if o == nil || IsNil(o.FeedbackUrl) {
		var ret string
		return ret
	}
	return *o.FeedbackUrl
}

// GetFeedbackUrlOk returns a tuple with the FeedbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetFeedbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FeedbackUrl) {
		return nil, false
	}
	return o.FeedbackUrl, true
}

// HasFeedbackUrl returns a boolean if a field has been set.
func (o *IPinfo) HasFeedbackUrl() bool {
	if o != nil && !IsNil(o.FeedbackUrl) {
		return true
	}

	return false
}

// SetFeedbackUrl gets a reference to the given string and assigns it to the FeedbackUrl field.
func (o *IPinfo) SetFeedbackUrl(v string) {
	o.FeedbackUrl = &v
}

// GetExitIp returns the ExitIp field value if set, zero value otherwise.
func (o *IPinfo) GetExitIp() string {
	if o == nil || IsNil(o.ExitIp) {
		var ret string
		return ret
	}
	return *o.ExitIp
}

// GetExitIpOk returns a tuple with the ExitIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetExitIpOk() (*string, bool) {
	if o == nil || IsNil(o.ExitIp) {
		return nil, false
	}
	return o.ExitIp, true
}

// HasExitIp returns a boolean if a field has been set.
func (o *IPinfo) HasExitIp() bool {
	if o != nil && !IsNil(o.ExitIp) {
		return true
	}

	return false
}

// SetExitIp gets a reference to the given string and assigns it to the ExitIp field.
func (o *IPinfo) SetExitIp(v string) {
	o.ExitIp = &v
}

// GetCapital returns the Capital field value if set, zero value otherwise.
func (o *IPinfo) GetCapital() string {
	if o == nil || IsNil(o.Capital) {
		var ret string
		return ret
	}
	return *o.Capital
}

// GetCapitalOk returns a tuple with the Capital field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCapitalOk() (*string, bool) {
	if o == nil || IsNil(o.Capital) {
		return nil, false
	}
	return o.Capital, true
}

// HasCapital returns a boolean if a field has been set.
func (o *IPinfo) HasCapital() bool {
	if o != nil && !IsNil(o.Capital) {
		return true
	}

	return false
}

// SetCapital gets a reference to the given string and assigns it to the Capital field.
func (o *IPinfo) SetCapital(v string) {
	o.Capital = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *IPinfo) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *IPinfo) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *IPinfo) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetCountryName returns the CountryName field value if set, zero value otherwise.
func (o *IPinfo) GetCountryName() string {
	if o == nil || IsNil(o.CountryName) {
		var ret string
		return ret
	}
	return *o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCountryNameOk() (*string, bool) {
	if o == nil || IsNil(o.CountryName) {
		return nil, false
	}
	return o.CountryName, true
}

// HasCountryName returns a boolean if a field has been set.
func (o *IPinfo) HasCountryName() bool {
	if o != nil && !IsNil(o.CountryName) {
		return true
	}

	return false
}

// SetCountryName gets a reference to the given string and assigns it to the CountryName field.
func (o *IPinfo) SetCountryName(v string) {
	o.CountryName = &v
}

// GetCountryRegion returns the CountryRegion field value if set, zero value otherwise.
func (o *IPinfo) GetCountryRegion() string {
	if o == nil || IsNil(o.CountryRegion) {
		var ret string
		return ret
	}
	return *o.CountryRegion
}

// GetCountryRegionOk returns a tuple with the CountryRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCountryRegionOk() (*string, bool) {
	if o == nil || IsNil(o.CountryRegion) {
		return nil, false
	}
	return o.CountryRegion, true
}

// HasCountryRegion returns a boolean if a field has been set.
func (o *IPinfo) HasCountryRegion() bool {
	if o != nil && !IsNil(o.CountryRegion) {
		return true
	}

	return false
}

// SetCountryRegion gets a reference to the given string and assigns it to the CountryRegion field.
func (o *IPinfo) SetCountryRegion(v string) {
	o.CountryRegion = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *IPinfo) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *IPinfo) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *IPinfo) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *IPinfo) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *IPinfo) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *IPinfo) SetDomainName(v string) {
	o.DomainName = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *IPinfo) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *IPinfo) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *IPinfo) SetCurrency(v string) {
	o.Currency = &v
}

// GetFlagUrl returns the FlagUrl field value if set, zero value otherwise.
func (o *IPinfo) GetFlagUrl() string {
	if o == nil || IsNil(o.FlagUrl) {
		var ret string
		return ret
	}
	return *o.FlagUrl
}

// GetFlagUrlOk returns a tuple with the FlagUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetFlagUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FlagUrl) {
		return nil, false
	}
	return o.FlagUrl, true
}

// HasFlagUrl returns a boolean if a field has been set.
func (o *IPinfo) HasFlagUrl() bool {
	if o != nil && !IsNil(o.FlagUrl) {
		return true
	}

	return false
}

// SetFlagUrl gets a reference to the given string and assigns it to the FlagUrl field.
func (o *IPinfo) SetFlagUrl(v string) {
	o.FlagUrl = &v
}

// GetDomains returns the Domains field value if set, zero value otherwise.
func (o *IPinfo) GetDomains() []string {
	if o == nil || IsNil(o.Domains) {
		var ret []string
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *IPinfo) HasDomains() bool {
	if o != nil && !IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *IPinfo) SetDomains(v []string) {
	o.Domains = v
}

// GetCallCodes returns the CallCodes field value if set, zero value otherwise.
func (o *IPinfo) GetCallCodes() []string {
	if o == nil || IsNil(o.CallCodes) {
		var ret []string
		return ret
	}
	return o.CallCodes
}

// GetCallCodesOk returns a tuple with the CallCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPinfo) GetCallCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.CallCodes) {
		return nil, false
	}
	return o.CallCodes, true
}

// HasCallCodes returns a boolean if a field has been set.
func (o *IPinfo) HasCallCodes() bool {
	if o != nil && !IsNil(o.CallCodes) {
		return true
	}

	return false
}

// SetCallCodes gets a reference to the given []string and assigns it to the CallCodes field.
func (o *IPinfo) SetCallCodes(v []string) {
	o.CallCodes = v
}

func (o IPinfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPinfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeedbackUrl) {
		toSerialize["feedback_url"] = o.FeedbackUrl
	}
	if !IsNil(o.ExitIp) {
		toSerialize["exit_ip"] = o.ExitIp
	}
	if !IsNil(o.Capital) {
		toSerialize["capital"] = o.Capital
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.CountryName) {
		toSerialize["country_name"] = o.CountryName
	}
	if !IsNil(o.CountryRegion) {
		toSerialize["country_region"] = o.CountryRegion
	}
	if !IsNil(o.TimeZone) {
		toSerialize["time_zone"] = o.TimeZone
	}
	if !IsNil(o.DomainName) {
		toSerialize["domain_name"] = o.DomainName
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.FlagUrl) {
		toSerialize["flag_url"] = o.FlagUrl
	}
	if !IsNil(o.Domains) {
		toSerialize["domains"] = o.Domains
	}
	if !IsNil(o.CallCodes) {
		toSerialize["call_codes"] = o.CallCodes
	}
	return toSerialize, nil
}

type NullableIPinfo struct {
	value *IPinfo
	isSet bool
}

func (v NullableIPinfo) Get() *IPinfo {
	return v.value
}

func (v *NullableIPinfo) Set(val *IPinfo) {
	v.value = val
	v.isSet = true
}

func (v NullableIPinfo) IsSet() bool {
	return v.isSet
}

func (v *NullableIPinfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPinfo(val *IPinfo) *NullableIPinfo {
	return &NullableIPinfo{value: val, isSet: true}
}

func (v NullableIPinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPinfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
