/* tslint:disable */
/* eslint-disable */
/**
 * Geolocate API
 * GeolocateAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ASN {
    'autonomous_system_number'?: number;
    'autonomous_system_organization'?: string;
}
export interface Agent {
    'is_agent'?: boolean;
    'service_name'?: string;
}
export interface IPinfo {
    'feedback_url'?: string;
    'exit_ip'?: string;
    'capital'?: string;
    'country_code'?: string;
    'country_name'?: string;
    'country_region'?: string;
    'time_zone'?: string;
    'domain_name'?: string;
    'currency'?: string;
    'flag_url'?: string;
    'domains'?: Array<string>;
    'call_codes'?: Array<string>;
}
export interface Privacy {
    'is_proxy'?: boolean;
    'is_relay'?: boolean;
    'is_tor'?: boolean;
    'service_name'?: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get ASN information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aSNExitIP: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/asn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get ASN information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aSNGivenIP: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('aSNGivenIP', 'ip', ip)
            const localVarPath = `/asn/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get agent information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentExitIP: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/agent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get agent information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentGivenIP: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('agentGivenIP', 'ip', ip)
            const localVarPath = `/agent/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateExitIP: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/geolocate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information about given domain
         * @param {string} domain Interested domain name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateGivenDomain: async (domain: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('geolocateGivenDomain', 'domain', domain)
            const localVarPath = `/geolocate/domain/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateGivenIP: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('geolocateGivenIP', 'ip', ip)
            const localVarPath = `/geolocate/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get privacy information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        privacyExitIP: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/privacy`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get privacy information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        privacyGivenIP: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('privacyGivenIP', 'ip', ip)
            const localVarPath = `/privacy/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get ASN information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aSNExitIP(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ASN>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aSNExitIP(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.aSNExitIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get ASN information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async aSNGivenIP(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ASN>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.aSNGivenIP(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.aSNGivenIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get agent information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentExitIP(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Agent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentExitIP(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.agentExitIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get agent information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async agentGivenIP(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Agent>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.agentGivenIP(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.agentGivenIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geolocateExitIP(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IPinfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geolocateExitIP(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.geolocateExitIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get information about given domain
         * @param {string} domain Interested domain name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geolocateGivenDomain(domain: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IPinfo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geolocateGivenDomain(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.geolocateGivenDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async geolocateGivenIP(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IPinfo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.geolocateGivenIP(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.geolocateGivenIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get privacy information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async privacyExitIP(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Privacy>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.privacyExitIP(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.privacyExitIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get privacy information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async privacyGivenIP(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Privacy>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.privacyGivenIP(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.privacyGivenIP']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Get ASN information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aSNExitIP(options?: RawAxiosRequestConfig): AxiosPromise<ASN> {
            return localVarFp.aSNExitIP(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get ASN information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        aSNGivenIP(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<ASN> {
            return localVarFp.aSNGivenIP(ip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get agent information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentExitIP(options?: RawAxiosRequestConfig): AxiosPromise<Agent> {
            return localVarFp.agentExitIP(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get agent information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        agentGivenIP(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<Agent> {
            return localVarFp.agentGivenIP(ip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateExitIP(options?: RawAxiosRequestConfig): AxiosPromise<IPinfo> {
            return localVarFp.geolocateExitIP(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information about given domain
         * @param {string} domain Interested domain name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateGivenDomain(domain: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<IPinfo>> {
            return localVarFp.geolocateGivenDomain(domain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        geolocateGivenIP(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<IPinfo> {
            return localVarFp.geolocateGivenIP(ip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get privacy information about your exit IP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        privacyExitIP(options?: RawAxiosRequestConfig): AxiosPromise<Privacy> {
            return localVarFp.privacyExitIP(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get privacy information about given IP
         * @param {string} ip Interested IP address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        privacyGivenIP(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<Privacy> {
            return localVarFp.privacyGivenIP(ip, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Get ASN information about your exit IP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aSNExitIP(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).aSNExitIP(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get ASN information about given IP
     * @param {string} ip Interested IP address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public aSNGivenIP(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).aSNGivenIP(ip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get agent information about your exit IP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentExitIP(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).agentExitIP(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get agent information about given IP
     * @param {string} ip Interested IP address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public agentGivenIP(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).agentGivenIP(ip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information about your exit IP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public geolocateExitIP(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).geolocateExitIP(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information about given domain
     * @param {string} domain Interested domain name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public geolocateGivenDomain(domain: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).geolocateGivenDomain(domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information about given IP
     * @param {string} ip Interested IP address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public geolocateGivenIP(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).geolocateGivenIP(ip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get privacy information about your exit IP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public privacyExitIP(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).privacyExitIP(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get privacy information about given IP
     * @param {string} ip Interested IP address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public privacyGivenIP(ip: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).privacyGivenIP(ip, options).then((request) => request(this.axios, this.basePath));
    }
}



