# coding: utf-8

"""
    Geolocate API

    GeolocateAPI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.privacy import Privacy

class TestPrivacy(unittest.TestCase):
    """Privacy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Privacy:
        """Test Privacy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Privacy`
        """
        model = Privacy()
        if include_optional:
            return Privacy(
                is_proxy = True,
                is_relay = True,
                is_tor = True,
                service_name = ''
            )
        else:
            return Privacy(
        )
        """

    def testPrivacy(self):
        """Test Privacy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
