# coding: utf-8

"""
    Geolocate API

    GeolocateAPI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_pinfo import IPinfo

class TestIPinfo(unittest.TestCase):
    """IPinfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IPinfo:
        """Test IPinfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPinfo`
        """
        model = IPinfo()
        if include_optional:
            return IPinfo(
                feedback_url = '',
                exit_ip = '',
                capital = '',
                country_code = '',
                country_name = '',
                country_region = '',
                time_zone = '',
                domain_name = '',
                currency = '',
                flag_url = '',
                domains = [
                    ''
                    ],
                call_codes = [
                    ''
                    ]
            )
        else:
            return IPinfo(
        )
        """

    def testIPinfo(self):
        """Test IPinfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
