# coding: utf-8

"""
    Geolocate API

    GeolocateAPI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_a_sn_exit_ip(self) -> None:
        """Test case for a_sn_exit_ip

        Get ASN information about your exit IP
        """
        pass

    def test_a_sn_given_ip(self) -> None:
        """Test case for a_sn_given_ip

        Get ASN information about given IP
        """
        pass

    def test_agent_exit_ip(self) -> None:
        """Test case for agent_exit_ip

        Get agent information about your exit IP
        """
        pass

    def test_agent_given_ip(self) -> None:
        """Test case for agent_given_ip

        Get agent information about given IP
        """
        pass

    def test_geolocate_exit_ip(self) -> None:
        """Test case for geolocate_exit_ip

        Get information about your exit IP
        """
        pass

    def test_geolocate_given_domain(self) -> None:
        """Test case for geolocate_given_domain

        Get information about given domain
        """
        pass

    def test_geolocate_given_ip(self) -> None:
        """Test case for geolocate_given_ip

        Get information about given IP
        """
        pass

    def test_privacy_exit_ip(self) -> None:
        """Test case for privacy_exit_ip

        Get privacy information about your exit IP
        """
        pass

    def test_privacy_given_ip(self) -> None:
        """Test case for privacy_given_ip

        Get privacy information about given IP
        """
        pass


if __name__ == '__main__':
    unittest.main()
